//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramConsultancyAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InquiryDetail
    {
        public int Id { get; set; }
        public string InquiryFor { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Rupees { get; set; }
        public string EMI { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
